repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^.+\.py$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - --quiet-level=2
        exclude_types: [csv, json]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks: 
      - id: mypy
        name: mypy
        entry: mypy
        additional_dependencies: [types-python-slugify]
        files: ^.+\.py$
 