repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.259
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^.+\.py$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args:
          - --quiet-level=2
        exclude_types: [csv, json]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks: 
      - id: mypy
        name: mypy
        entry: mypy
        additional_dependencies: [types-requests]
        files: ^.+\.py$
 